<?php

namespace App\Models;

use App\Enums\StampMethod;
use Database\Factories\StampFactory;
use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * One stamp. `client_uuid` is generated by the merchant app per operation and
 * is unique here, so a double tap or a retried request cannot add two.
 *
 * A wrong stamp is cancelled from the dashboard with a reason — marked, never
 * deleted, and never after the reward was handed over.
 */
#[Fillable(['card_cycle_id', 'card_id', 'customer_id', 'merchant_id', 'method', 'client_uuid', 'stamped_at'])]
class Stamp extends Model
{
    /** @use HasFactory<StampFactory> */
    use HasFactory;

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'method' => StampMethod::class,
            'stamped_at' => 'datetime',
            'cancelled_at' => 'datetime',
        ];
    }

    public function isCancelled(): bool
    {
        return $this->cancelled_at !== null;
    }

    /**
     * @return BelongsTo<CardCycle, $this>
     */
    public function cardCycle(): BelongsTo
    {
        return $this->belongsTo(CardCycle::class);
    }

    /**
     * @return BelongsTo<Card, $this>
     */
    public function card(): BelongsTo
    {
        return $this->belongsTo(Card::class);
    }

    /**
     * @return BelongsTo<Customer, $this>
     */
    public function customer(): BelongsTo
    {
        return $this->belongsTo(Customer::class);
    }

    /**
     * @return BelongsTo<Merchant, $this>
     */
    public function merchant(): BelongsTo
    {
        return $this->belongsTo(Merchant::class);
    }

    /**
     * @return BelongsTo<AdminUser, $this>
     */
    public function cancelledBy(): BelongsTo
    {
        return $this->belongsTo(AdminUser::class, 'cancelled_by_admin_id');
    }
}
